const data = [
  { firstName: "James" },
  { lastName: "Harden" },
  { numberAndTeam: "13 G / HOU" },
  { points: 28.0 },
  { firstName: "DeAndre" },
  { lastName: "Jordan" },
  { numberAndTeam: "6 C / LAC" },
  { Rebounds: 14.0 },
  { firstName: "Russel" },
  { lastName: "Westbrook" },
  { numberAndTeam: "0 G / OKC" },
  { Assists: 10.0 },
  { firstName: "Russel" },
  { lastName: "Westbrook" },
  { numberAndTeam: "0 G / OKC" },
  { Steals: 2.4 },
  { firstName: "Kevin" },
  { lastName: "Durant" },
  { numberAndTeam: "35 F / OKC" },
  { points: 27.8 },
  { firstName: "Dwight" },
  { lastName: "Howard" },
  { numberAndTeam: "12 C / HOU" },
  { Rebounds: 12.0 },
  { firstName: "John" },
  { lastName: "Wall" },
  { numberAndTeam: "2 G / WAS" },
  { Assists: 9.9 },
  { firstName: "Ricky" },
  { lastName: "Rubio" },
  { numberAndTeam: "9 G / MIN" },
  { Steals: 2.2 },
  { firstName: "DeMarcus" },
  { lastName: "Cousins" },
  { numberAndTeam: "15 C-F / SAC" },
  { points: 26.8 },
  { firstName: "DeMarcus" },
  { lastName: "Cousins" },
  { numberAndTeam: "15 C-F / SAC" },
  { Rebounds: 11.1 },
  { firstName: "Chris" },
  { lastName: "Paul" },
  { numberAndTeam: "3 G / LAC" },
  { Assists: 9.4 },
  { firstName: "Chris" },
  { lastName: "Paul" },
  { numberAndTeam: "3 G / LAC" },
  { Steals: 2.2 },
  { firstName: "LeBron" },
  { lastName: "James" },
  { numberAndTeam: "23 F / CLE" },
  { points: 25.0 },
  { firstName: "Hassan" },
  { lastName: "Whiteside" },
  { numberAndTeam: "21 C / MIA" },
  { Rebounds: 11.0 },
  { firstName: "Ricky" },
  { lastName: "Rubio" },
  { numberAndTeam: "9 G / MIN" },
  { Assists: 8.6 },
  { firstName: "Stephen" },
  { lastName: "Curry" },
  { numberAndTeam: "30 G / GSW" },
  { Steals: 2.1 },
];

export default data;

